package markdown

import (
	"github.com/alecthomas/chroma/v2"
	chromastyles "github.com/alecthomas/chroma/v2/styles"
)

func init() {
	chromastyles.Register(chroma.MustNewStyle("tokyonight-night", chroma.StyleEntries{
		chroma.Background:               "#c0caf5 bg:#1a1b26",
		chroma.Text:                     "#c0caf5",
		chroma.TextWhitespace:           "#3b4261",
		chroma.Error:                    "#f7768e",
		chroma.Comment:                  "italic #565f89",
		chroma.CommentPreproc:           "#7aa2f7",
		chroma.Keyword:                  "bold #bb9af7",
		chroma.KeywordConstant:          "#ff9e64",
		chroma.KeywordDeclaration:       "bold #7aa2f7",
		chroma.KeywordNamespace:         "#7aa2f7",
		chroma.KeywordPseudo:            "#bb9af7",
		chroma.KeywordReserved:          "#bb9af7",
		chroma.KeywordType:              "#2ac3de",
		chroma.Operator:                 "#89ddff",
		chroma.OperatorWord:             "bold #89ddff",
		chroma.Punctuation:              "#c0caf5",
		chroma.Name:                     "#c0caf5",
		chroma.NameAttribute:            "#73daca",
		chroma.NameBuiltin:              "#7aa2f7",
		chroma.NameBuiltinPseudo:        "#7aa2f7",
		chroma.NameClass:                "#7aa2f7",
		chroma.NameConstant:             "#ff9e64",
		chroma.NameDecorator:            "#7aa2f7",
		chroma.NameEntity:               "#73daca",
		chroma.NameException:            "#f7768e",
		chroma.NameFunction:             "#7aa2f7",
		chroma.NameLabel:                "#7dcfff",
		chroma.NameNamespace:            "#7aa2f7",
		chroma.NameOther:                "#c0caf5",
		chroma.NameProperty:             "#73daca",
		chroma.NameTag:                  "#7aa2f7",
		chroma.NameVariable:             "#f7768e",
		chroma.NameVariableClass:        "#f7768e",
		chroma.NameVariableGlobal:       "#f7768e",
		chroma.NameVariableInstance:     "#f7768e",
		chroma.Literal:                  "#9ece6a",
		chroma.LiteralDate:              "#e0af68",
		chroma.LiteralString:            "#9ece6a",
		chroma.LiteralStringAffix:       "#9ece6a",
		chroma.LiteralStringBacktick:    "#9ece6a",
		chroma.LiteralStringChar:        "#9ece6a",
		chroma.LiteralStringDelimiter:   "#9ece6a",
		chroma.LiteralStringDoc:         "italic #565f89",
		chroma.LiteralStringDouble:      "#9ece6a",
		chroma.LiteralStringEscape:      "#bb9af7",
		chroma.LiteralStringHeredoc:     "#9ece6a",
		chroma.LiteralStringInterpol:    "#e0af68",
		chroma.LiteralStringOther:       "#9ece6a",
		chroma.LiteralStringRegex:       "#b4f9f8",
		chroma.LiteralStringSingle:      "#9ece6a",
		chroma.LiteralStringSymbol:      "#ff9e64",
		chroma.LiteralNumber:            "#ff9e64",
		chroma.LiteralNumberBin:         "#ff9e64",
		chroma.LiteralNumberFloat:       "#ff9e64",
		chroma.LiteralNumberHex:         "#ff9e64",
		chroma.LiteralNumberInteger:     "#ff9e64",
		chroma.LiteralNumberIntegerLong: "#ff9e64",
		chroma.LiteralNumberOct:         "#ff9e64",
		chroma.GenericDeleted:           "#f7768e",
		chroma.GenericEmph:              "italic",
		chroma.GenericError:             "#f7768e",
		chroma.GenericHeading:           "bold #7aa2f7",
		chroma.GenericInserted:          "#9ece6a",
		chroma.GenericOutput:            "#565f89",
		chroma.GenericPrompt:            "bold #2ac3de",
		chroma.GenericStrong:            "bold",
		chroma.GenericSubheading:        "bold #7aa2f7",
		chroma.GenericTraceback:         "#f7768e",
	}))
}
